// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Doctor struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Rate        *float64  `json:"rate"`
	Reviews     []*string `json:"reviews"`
	Price       float64   `json:"price"`
	Specialties []string  `json:"specialties"`
}

type NewDoctor struct {
	Name        string   `json:"name"`
	Price       float64  `json:"price"`
	Specialties []string `json:"specialties"`
}
